name: musicautobot2
channels:
  - fastai
  - pytorch
  - defaults
dependencies:
  - pytorch
  - fastai==1.0.61
  - jupyter
  - ipyparallel
  - pip
  - python>=3.6

  - pip:
      - music21
      - pebble
      - OpenNMT-py
